FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /todolist-api

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /todolist-api .
EXPOSE 8080
CMD ["./todolist-api"]